include ./bloodmoon.conf
font_family       Monaspace Krypton Frozen Light
bold_font         Monaspace Krypton Frozen
italic_font       Monaspace Krypton Frozen Light Italic
bold_italic_font  Monaspace Krypton Frozen Italic
font_size 13.0
cursor_shape block
enable_audio_bell no
allow_remote_control yes
listen_on unix:/tmp/kitty-clockwork
enabled_layouts splits,tall,stack,fat,grid,horizontal,vertical
